# Multiples of 3 and 5

## Problem 1

If we list all the natural numbers below 10 that are multiples of 3 or 5, we
get 3; 5; 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5
below 1000.

In [0]:
import time

In [0]:
def euler_01(n):
    return sum(filter(lambda x: (x % 5)*(x % 3)== 0, range(n)))

In [11]:
start = time.time()    
result = euler_01(1000) # sequential version
end = time.time()
print(f'The result is {result}')
print(f'Time to complete in sequential version: {end - start:.4f}s\n')

The result is 233168
Time to complete in sequential version: 0.0010s

# Even Fibonacci numbers

## Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
> $1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dotsc$

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [0]:
class Fibs:
    def __init__(self, a = 0, b = 1 ):
        self.a = a
        self.b = b
    def __next__(self):
        aux = self.a
        self.a, self.b = self.b, self.a + self.b
        return aux
    def __iter__(self):
        return self

In [0]:
def euler_02(ub):
    fibs = Fibs()
    fib = next(fibs)
    accum = 0 
    while fib < ub:
        if fib % 2 == 0: accum += fib
        fib = next(fibs)
    return accum

In [14]:
n = 4*10**6
start = time.time()    
result = euler_02(n) # sequential version
end = time.time()
print(f'Answer {result}')
print(f'Time to complete in sequential version: {end - start:.4f}s\n')

Answer 4613732
Time to complete in sequential version: 0.0001s