# Multiples of 3 and 5

## Problem 1

If we list all the natural numbers below 10 that are multiples of 3 or 5, we
get 3; 5; 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5
below 1000.

In [0]:
import time

In [0]:
def euler_01(n):
    return sum(filter(lambda x: (x % 5)*(x % 3)== 0, range(n)))

In [0]:
start = time.time()    
result = euler_01(1000) # sequential version
end = time.time()
print(f'Answer: {result}')
print(f'Time to complete: {end - start:.4f}s\n')

Answer: 233168
Time to complete: 0.0002s

# Even Fibonacci numbers

## Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
> $1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dotsc$

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [0]:
class Fibs:
    def __init__(self, a = 0, b = 1 ):
        self.a = a
        self.b = b
    def __next__(self):
        aux = self.a
        self.a, self.b = self.b, self.a + self.b
        return aux
    def __iter__(self):
        return self

In [0]:
def euler_02(ub):
    fibs = Fibs()
    fib = next(fibs)
    accum = 0 
    while fib < ub:
        if fib % 2 == 0: accum += fib
        fib = next(fibs)
    return accum

In [0]:
n = 4*10**6
start = time.time()    
result = euler_02(n) # sequential version
end = time.time()
print(f'Answer: {result}')
print(f'Time to complete: {end - start:.4f}s\n')

Answer 4613732
Time to complete: 0.0001s

#Largest prime factor

## Problem 3

The prime factors of $13195$ are $5, 7, 13$ and $29$.

What is the largest prime factor of the number $600851475143$ ?

In [0]:
from typing import List
import math

In [0]:
def divisors(n: int) -> List[int]:
    """Returns the list of divisors of a positive integer.
     Example: >>>divisors(10): [1, 2, 5, 10]"""
    ls = []
    d = math.ceil(math.sqrt(n))
    ls = [i for i in range(1, d) if n % i == 0]
    rs = [n // i for i in ls]
    if d**2 == n and n % d == 0:
        ls.append(d)
    return ls + rs[::-1]

In [0]:
def q(n: int) -> int:
    """
    Returns the smallest divisor of n bigger than 1.
    For example q(100) = 2, q(15) = 3, q(125) = 5.  
    """
    assert (n > 1), "Not a valid input n = {} must be > 1".format(n)
    ub = math.ceil(math.sqrt(n))
    if n % 2 == 0: return 2
    d = n    
    for i in range(3, ub + 1, 2):
        if n % i == 0:
            d = i
            break
    return d

def isPrime(n: int) -> bool:
    """Return True if n is prime, False otherwise"""
    n = abs(n)
    if n == 0:
        return False
    if n == 1:
       return False
    if n in [2, 3, 5]: 
      return True
    return n == q(n)

In [0]:
def euler_03 (n):
  ls = divisors (n) [:: -1]
  for i in ls:
    if isPrime(i): 
      return i

In [0]:
n = 600851475143  
start = time.time()    
result = euler_03(n) # sequential version
end = time.time()
print(f'Answer: {result}')
print(f'Time to complete: {end - start:.4f}s\n')

Answer: 6857
Time to complete: 0.0982s